### ISSUE TITLE
Category menu does not work in multilingual sites

### ISSUE THREAD

**Issue by stephangrass** [pixelant/pxa_dealers#49]
Hello, I have created a category menu. It works in the default language. The menu is not displayed in other languages. The categories and all elements have been localized.

**Comment by stephangrass** [comment]
No reaction? Pity!
...

**Comment by MattiasNilsson** [comment]
@stephangrass Do you use languages layers with mixed mode?

**Comment by stephangrass** [comment]
$this->settings['demand'] in the categoriesFilterAction will return the Category-Id's of the default language, and $this->categoriesRepository->findDemanded use this id's directly.

**Comment by MattiasNilsson** [comment]
Have you tried changing the Categories in TypoScript?

![Screenshot 2022-12-21 at 08 23 38](https://user-images.githubusercontent.com/1718315/208845053-7ae37dab-2087-4eb1-862b-8d3414661af5.png)

**Comment by stephangrass** [comment]
Yes, that doesn't seem to have any effect.

I think you have to do something like in tx_news by Georg Ringer in the repository or controller:
https://github.com/georgringer/news/blob/main/Classes/Domain/Repository/CategoryRepository.php#L193

**Comment by MattiasNilsson** [comment]
@stephangrass A new release is out with the fix: https://github.com/pixelant/pxa_dealers/releases/tag/v4.2.2
